from __future__ import annotations

from typing import Any

from app.ui.html import css_class, h, json_dumps_safe, safe_link, to_plain


def badge(label: Any, tone: str = "info") -> str:
    label_text = str(label or "unknown").replace("_", " ")
    return f'<span class="badge {h(css_class(tone or label_text))}">{h(label_text)}</span>'


def card(title: str, body: str, *, subtitle: str | None = None, action: str | None = None) -> str:
    subtitle_html = f'<div class="subtitle">{h(subtitle)}</div>' if subtitle else ""
    action_html = action or ""
    return (
        '<section class="card">'
        '<div class="card-header">'
        f'<div class="card-title"><h2>{h(title)}</h2>{subtitle_html}</div>'
        f'{action_html}'
        '</div>'
        f'{body}'
        '</section>'
    )


def metric_card(label: str, value: Any, *, note: str | None = None) -> str:
    note_html = f'<div class="metric-note">{h(note)}</div>' if note else ""
    return (
        '<div class="metric">'
        f'<div class="metric-label">{h(label)}</div>'
        f'<div class="metric-value">{h(value, default="0")}</div>'
        f'{note_html}'
        '</div>'
    )


def empty_state(message: str) -> str:
    return f'<div class="empty-state">{h(message)}</div>'


def json_details(title: str, value: Any, *, open_by_default: bool = False) -> str:
    open_attr = " open" if open_by_default else ""
    return (
        f'<details{open_attr}>'
        f'<summary>{h(title)}</summary>'
        f'<pre>{h(json_dumps_safe(value))}</pre>'
        '</details>'
    )


def simple_table(headers: list[str], rows: list[list[Any]]) -> str:
    if not rows:
        return empty_state("No records available.")
    head_html = "".join(f"<th>{h(header)}</th>" for header in headers)
    row_html = ""
    for row in rows:
        cells = "".join(f"<td>{cell if isinstance(cell, SafeHTML) else h(cell)}</td>" for cell in row)
        row_html += f"<tr>{cells}</tr>"
    return f'<div class="table-wrap"><table><thead><tr>{head_html}</tr></thead><tbody>{row_html}</tbody></table></div>'


class SafeHTML(str):
    """Marker for HTML fragments generated by trusted render helpers."""


def link_cell(url: Any, label: Any | None = None) -> SafeHTML:
    return SafeHTML(safe_link(url, label))


def badge_cell(label: Any, tone: str | None = None) -> SafeHTML:
    return SafeHTML(badge(label, tone or str(label or "info")))


def list_chips(values: list[Any] | None) -> str:
    values = [item for item in (values or []) if item]
    if not values:
        return ""
    return '<div class="chips">' + "".join(f'<span class="chip">{h(item)}</span>' for item in values[:12]) + '</div>'


def warnings_panel(warnings: list[Any] | None) -> str:
    warnings = [str(item) for item in (warnings or []) if item]
    if not warnings:
        return ""
    items = "".join(f'<div class="warning-item">{h(item)}</div>' for item in warnings)
    return card("Warnings", f'<div class="warning-list">{items}</div>', subtitle="Non-fatal issues returned by the API.")


def dict_list(value: Any) -> list[dict[str, Any]]:
    plain = to_plain(value)
    if isinstance(plain, list):
        return [item for item in plain if isinstance(item, dict)]
    return []
